### PR TITLE
Update scorecard.yml

### PR DESCRIPTION
**Pull request by Wisammad**

### CODE REVIEW

**Comment by RestartDK** [comment]
by the way I noticed you were running the workflow on the wrong branch, make sure to choose the correct branch when running this

**Comment by Wisammad** [comment]
Can you merge this one, its the updated official one?

**Comment by Wisammad** [comment]
The error is because its not on the main branch, once it is should work Id assume

**Comment by RestartDK** [comment]
will merge it now you are right it doesn't work without being on main

**Pull request merged**
